### ISSUE TITLE
Fallback fuzzy matching in SearchRequest message should be inverted

### ISSUE THREAD

**Issue by blu3id** [wardle/terminology#1]
In the `SearchRequest` message `use_fallback_fuzzy_matching` is described as "use fuzzy matching only if no results at all without fuzzy, default true" this presents a logical issue when parsing the message as Protocol Buffers don't allow for 3 state `bool` values and so a value of `false` is assigned to unset `bool` fields[[1]](https://developers.google.com/protocol-buffers/docs/proto3#default). 

Therefore it is impossible to determine if the field has intentionally been set to `false` form the default state of `true` or if the field is unset (and so should be in default state of `true`).

I propose that this field be inverted (so as to have a default state of `false` but still default to enabling fallback fuzzy matching). I would suggest a new name of `suppress_fallback_fuzzy_matching` with a default of `false` and a description of "Prevent the automatic use of fuzzy matching if no results at all without fuzzy, default false".

**Comment by wardle** [comment]
Thanks Mike. You're right, of course. I have simply ported the old API definition from the lucene-based java search as a placeholder and haven't given it much thought yet. 

I like your idea, but given protocol buffers support enums, we can simplify the API by using an enum-based preference. However, I do wonder whether it is needed at all, and whether we can just default until we have a use-case. Certainly when I've been a client of the old API, I haven't yet needed to change from the defaults. That said, my use case has mainly been interactive use whereas I can see benefit in tweaking the search options for, say, batch use processing free-text entered historically. 

It is a similar issue with the choice to search fully specified names (I can't see that I've ever used that and cannot actually see a use-case, so I'm tempted to remove it and simplify the API) and whether to search inactive terms (but that one already has the right semantics for a default value given the name).

As such, I've turned it into an enum for fuzziness and removed FSN search.
